### PR TITLE
fix(#61): args options not working

### LINKED ISSUE #61: Can no longer pass `args` to pytest runner
## Summary 
- After updating the plugin, additional args pass to pytest no longer run and out put an error

## Config
```lua
  -- For Python test
  {
    "nvim-neotest/neotest",
    dependencies = {
      "nvim-neotest/neotest-python",
    },
    lazy = true,
    opts = function(_, opts)
      table.insert(
        opts.adapters,
        require("neotest-python")({
          -- Extra arguments for nvim-dap configuration
          -- See https://github.com/microsoft/debugpy/wiki/Debug-configuration-settings for values
          dap = {
            justMyCode = false,
            console = "integratedTerminal",
          },
          args = { "--log-level", "DEBUG", "-s" },
          runner = "pytest",
        })
      )
    end,
  },
```
## Error output
```shell
usage: neotest.py [-h] --runner RUNNER --results-file RESULTS_FILE --stream-file STREAM_FILE
                  [--emit-parameterized-ids]
                  [args ...]
neotest.py: error: unrecognized arguments: --log-level -s /Users/haonguyen/Code/rapiddweller/rd-lib-datamimic/tests/integration_tests/datamimic_demo/test_datamimic_demo.py::TestDatamim
icDemo::test_g_domains
```

### PR DESCRIPTION
**Pull request by nguyenanhhao221**
fix #61

### CODE REVIEW

File: lua/neotest-python/init.lua [hunk 1]
```diff
@@ -151,6 +151,7 @@ function PythonNeotestAdapter.build_spec(args)
     stream_path,
     "--runner",
     runner,
+    "--"
   })
   if pytest_discover_instances then
```
Comment (rcarriga) [inline lua/neotest-python/init.lua:156]: The `--` has to be added after this `if` block

**Review by rcarriga — CHANGES_REQUESTED** [review]
Thanks for the PR! Just one small change
